### PR TITLE
Bug in boundary checking in the CBORParser

### PR DESCRIPTION
**Pull request by stevegury**
When reading from an composite inputStream, there's a bug during the checking
of the buffer boundary. This may lead to an ArrayIndexOutOfBoundsException.

I build a test case that expose the bug and fixed the bound checking.

### CODE REVIEW

**Comment by stevegury** [comment]
Hey @cowtowncoder, did you have the chance to look at this PR? (no rush)

**Comment by cowtowncoder** [comment]
Ah. Thank you for reminding! This did slip through, I did see original creation, but forgot to follow up.

**Comment by cowtowncoder** [comment]
Big thank you for finding and fixing this problem. I verified and it is a regression from 2.5, related to symbol table changes and performance optimizations; so it does not affect pre-2.6 versions.
Fix will be in 2.6.2, which will take couple of weeks as I am leaving on vacation now, but should be released around mid-September at least, due to severity of this problem.

**Comment by stevegury** [comment]
I can work with the snapshot version in the meantime.
Have a good vacation!

**Pull request merged**
